# Generated by Django 4.0.4 on 2022-07-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_agree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('email', models.CharField(max_length=500)),
                ('dese', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
